# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hanna Taylor
email: hanna.taylor@icloud.com
description: Full Stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: hanna__taylor
github_username:  hannataylor
linkedin_username: hannataylor
instagram_username: hanna__taylor

# Plugins

# Build settings
markdown: kramdown

# Handling Reading
include: ['_pages']
